language: python
os:
  - linux
python:
  - "2.7"
# command to install dependencies
addons: 
    apt:
        packages:
        - llvm
        - python-pip
        - gfortran
        - libncurses5-dev
        - cmake
        - samtools
        - bowtie2
install: "pip install -r requirements.txt"
# command to run tests
script: pytest
